books/urls.py
from django.urls import path
from books import views

app_name = 'books'
urlpatterns = [
    path('catalogue/<int:user_id>/', views.render_book_catalogue, name='catalogue'),
    path('new/<int:user_id>/', views.render_create_book_form, name='new'),
    path('add/', views.process_create_book_form, name='add'),
    path('edit/<int:book_id>/', views.render_edit_book_form, name='edit'),
    path('save/<int:book_id>/', views.process_edit_book_form, name='save'),
    path('delete/<int:book_id>/', views.delete_book, name='delete'),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'
urlpatterns = [
    path('new/', views.render_register_user_form, name='new'),
    path('register/', views.process_register_user_form, name='register'),
    path('login/', views.process_login_user_form, name='login'),
    path('authorize/', views.render_login_user_form, name='authorize'),
]

books/models.py
from django.db import models
from users.models import User
# Create your models here.


class Book(models.Model):
    name = models.CharField(max_length=100)
    author = models.CharField(max_length=50)
    genre = models.CharField(max_length=50)
    language = models.CharField(max_length=50)
    publication_date = models.DateField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner')

    def __str__(self):
        return self.name + ' (' + self.author.first_name + ' ' + self.author.last_name + ')'

users/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=25)

    def __str__(self):
        return self.first_name + ' ----> ' + self.last_name

books/views.py
from django.shortcuts import render
from books.models import Book
from django.shortcuts import HttpResponseRedirect, reverse, HttpResponse


# Create your views here.


def render_book_catalogue(request, user_id):
    template = 'books/catalogue.html'
    context = {
        'catalogue': Book.objects.filter(owner_id=user_id),
        'user': user_id
    }
    return render(request, template, context)


def render_create_book_form(request, user_id):
    template = 'books/create_book_form.html'
    context = {
        'user': user_id
    }
    return render(request, template, context)


def process_create_book_form(request):
    if request.method == 'POST':
        new_book = Book(
            name=request.POST['name'],
            author=request.POST['author'],
            genre=request.POST['genre'],
            language=request.POST['language'],
            publication_date=request.POST['publication_date'],
            owneR_id=request.POST['owner_id'],
        )
        new_book.save()

        return HttpResponseRedirect(reverse('books:catalogue', kwargs={'user_id': new_book.owner.id}))
    return HttpResponse('Error: method not allowed.')


def render_edit_book_form(request, book_id):
    template = 'books/edit_book_form.html'
    context = {
        'book': Book.objects.get(id=book_id)
    }
    return render(request, template, context)


def process_edit_book_form(request, book_id):
    if request.method == 'POST':
        updated_book = Book.objects.get(id=book_id)
        updated_book.name = request.POST['name']
        updated_book.author = request.POST['author']
        updated_book.genre = request.POST['genre']
        updated_book.language = request.POST['language']
        updated_book.publication_date = request.POST['publication_date']
        updated_book.save()

        return HttpResponseRedirect(reverse('books:catalogue', kwargs={'user_id': updated_book.owner.id}))
    return HttpResponse('Error: method not allowed.')


def delete_book(request, book_id):
    deleted_book = Book.objects.get(id=book_id)
    deleted_book.delete()

    return HttpResponseRedirect(reverse('books:catalogue', kwargs={'user_id': deleted_book.owner.id}))

users/views.py
from users.models import User
from django.shortcuts import render
from django.shortcuts import HttpResponseRedirect, reverse, HttpResponse

# Create your views here.


def render_register_user_form(request):
    template = 'users/register_user_form.html'
    return render(request, template)


def process_register_user_form(request):
    if request.method == 'POST':
        new_user = User(
            first_name=request.POST['first_name'],
            last_name=request.POST['last_name'],
            email=request.POST['email'],
            password=request.POST['password']
        )
        new_user.save()

        return HttpResponseRedirect(reverse('users:login'))
    return HttpResponse('Error: method not allowed.')


def render_login_user_form(request):
    template = 'users/login_user_form.html'
    return render(request, template)


def process_login_user_form(request):
    if request.method == 'POST':
        try:
            user = User.objects.get(email=request.POST['email'], password=request.POST['password'])
        except User.DoesNotExist:
            return HttpResponse('User does not exist.')

        return HttpResponseRedirect(reverse('books:catalogue', kwargs={'user_pk': user.pk}))
    return HttpResponse('Error: method not allowed.')

books/templates/books/book_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Book</title>
</head>
<body>
    <h1>Add Book</h1>
        <form action="{% url 'books:add' %}" method="POST">{% csrf_token %}
            <input name="owner_id" value="{{ user }}" hidden>
            <p><label>Name: </label><input type="text" name="name"></p>
            <p><label>Author: </label><input type="text" name="author"></p>
            <p><label>Genre: </label><select name="genre">
                <option value="1">Horror</option>
                <option value="2">Fantasy</option>
                <option value="3">Mystery</option>
                <option value="4">Biography</option>
                <option value="5">Romance</option>
                <option value="6">Self Help</option>
                <option value="7">Text Book</option>
            </select></p>
            <p><label>Language: </label><select name="language">
                <option value="1">English</option>
                <option value="2">Spanish</option>
                <option value="3">French</option>
                <option value="4">German</option>
                <option value="5">Chinese</option>
                <option value="6">Japanese</option>
            </select></p>
            <p><label>Publication Date: </label><input type="date" name="publication_date"></p>
            <p><input type="submit" value="Add"></p>
        </form>
</body>
</html>

books/templates/books/catalogue.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Catalogue</title>
</head>
<body>
    <h1>Catalogue</h1>
    <h4><a href="{% url 'books:new ' user %}">Add a Book</a></h4>
    {% if catalogue %}
        {% for book in catalogue %}
        <p>{{ book.name }} --- {{ book.author }} (<a href="{% url ''books:edit' book.id%}">Edit</a>)(<a href="{% url 'books:delete' book.id %}">Delete</a>)</p>
        {% endfor %}
    {% else %}
        <p>You have'nt Books. Add One <a href="{% url 'books:new' user %}">Here</a>!</p>
    {% endif %}
</body>
</html>

users/templates/users/edit_book_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Edit Book</h1>
    <form action="{% url 'books:save' book.id %}" method="POST">{% csrf_token %}
        <p><label>Name: </label><input type="text" name="name" value="{{book.name}}"></p>
        <p><label>Author: </label><input type="text" name="author" value="{{book.author}}"></p>
        <p><label>Genre: </label><select name="genre">
            <option value="1" {% if book.genre == '1' %}selected="selected"{% endif %}>Horror</option>
            <option value="2" {% if book.genre == '2' %}selected="selected"{% endif %}>Fantasy</option>
            <option value="3" {% if book.genre == '3' %}selected="selected"{% endif %}>Mystery</option>
            <option value="4" {% if book.genre == '4' %}selected="selected"{% endif %}>Biography</option>
            <option value="5" {% if book.genre == '5' %}selected="selected"{% endif %}>Romance</option>
            <option value="6" {% if book.genre == '6' %}selected="selected"{% endif %}>Self Help</option>
            <option value="7" {% if book.genre == '7' %}selected="selected"{% endif %}>Text Book</option>
        </select></p>
        <p><label>Language: </label><select name="language">
            <option value="1" {% if book.language == '1' %}selected="selected"{% endif %}>English</option>
            <option value="2" {% if book.language == '2' %}selected="selected"{% endif %}>Spanish</option>
            <option value="3" {% if book.language == '3' %}selected="selected"{% endif %}>French</option>
            <option value="4" {% if book.language == '4' %}selected="selected"{% endif %}>German</option>
            <option value="5" {% if book.language == '5' %}selected="selected"{% endif %}>Chinese</option>
            <option value="6" {% if book.language == '6' %}selected="selected"{% endif %}>Japanese</option>
        </select></p>
        <p><label>Publication Date: </label><input type="date" name="publication_date" value="{{book.publication_date|date:'Y-m-d'}}"></p>
        <p><input type="submit" value="Save"></p>
    </form>
</body>
</html>

users/templates/users/login_user_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Login</title>
</head>
<body>
    <h1>Login</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <p><label>Email: </label><input type="text" name="email"></p>
        <p><label>Password:</label><input type="password" name="password"></p>
        <input type="submit" value="Login">
    </form>
</body>
</html>

users/templates/users/register_user_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Registration</title>
</head>
<body>
    <h1>Register Account</h1>
        <form action="{% url 'users:register' %}" method="POST">
            {% csrf_token %}
            <p><label>First Name: </label><input type="text" name="first_name"></p>
            <p><label>Last Name: </label><input type="text" name="last_name"></p>
            <p><label>Email: </label><input type="text" name="email"></p>
            <p><label>Password: </label><input type="password" name="password"></p>
            <p><input type="submit" value="Register"></p>
        </form>
</body>
</html>